[build]
command = "pnpm run build"
publish = ".next/standalone"

[build.environment]
NODE_VERSION = "18"

[env]
NODE_ENV = "production"

[[redirects]]
from = "https://aistone.org/*"
to = "https://www.aistone.org/:splat"
status = 301

[[redirects]]
from = "http://aistone.org/*"
to = "https://www.aistone.org/:splat"
status = 301

# 缓存配置
[[headers]]
for = "/*"
[headers.values]
Cache-Control = "public, max-age=3600" 